Allow usage of OCLC numbers as identifiers
medusa-project/book-tracker pull request #47
Opened 2024-01-17 18:54 UTC by gaurijo

This PR is for issue #8 

Summary of Changes:

- Modify placeholder in search box to include filtering by `oclc number(s)`
<img width="1108" alt="Screenshot 2024-01-17 at 10 42 10 AM" src="https://github.com/medusa-project/book-tracker/assets/103534307/0ba3066c-5609-4042-b0a8-16806826eb44">

- Include `oclc_number` in table results

<img width="1059" alt="Screenshot 2024-01-17 at 10 43 26 AM" src="https://github.com/medusa-project/book-tracker/assets/103534307/27661f4d-2eb2-45ca-beaa-df8367435e84">

- Update `BooksController#index` to query for oclc_numbers (which are found by setting `id.length == 8`)
- Include oclc_number for `compiling missing ids`
- Add `'OR oclc_number = ?'` in SQL query to find matching book records 
- Tests for each of the different `filtering queries` (bib, object, oclc)

2024-01-17 22:33 UTC, adolski requested changes

2024-01-17 22:33 UTC, adolski commented on test/controllers/books_controller_test.rb
> +    query = "#{@b6.oclc_number}\n#{@b5.oclc_number}"
We need to send this query to the controller. From this point, the test would proceed something like:
```ruby
query = "#{@b6.oclc_number}\n#{@b5.oclc_number}"
# (I changed the response format to JSON to make the result easier to parse.)
get books_url(q: query, format: :json)
response_body = JSON.parse(response.body)
assert_equal 2, response['numResults']
# maybe more thorough checks here, if you wanted to check for the specific books
```

BTW, if you don't have one installed yet, a browser plugin that can format+colorize JSON is helpful.

2024-01-17 22:33 UTC, adolski commented on test/controllers/books_controller_test.rb
> +    query = "#{@b6.obj_id}\n#{@b5.obj_id}"
(same as above)

2024-01-17 22:33 UTC, adolski commented on test/controllers/books_controller_test.rb
> +    query = "#{@b6.bib_id}\n#{@b5.bib_id}"
(same as above)

2024-01-17 23:21 UTC, gaurijo commented on test/controllers/books_controller_test.rb
> +    query = "#{@b6.oclc_number}\n#{@b5.oclc_number}"
Thanks, I definitely made the test more complicated than it needed to be. 

I updated it so each query calls on the controller. I added more specific assertions like:

```ruby
assert_equal @b6.obj_id, response_body['results'][0]['obj_id']
```

2024-01-18 21:15 UTC, merged

2024-01-18 21:15 UTC, adolski commented
Great work!